name: CI
on: push
jobs:
  installing_py:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        needs:
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest tests/test_handler/

  testing:
    runs-on: ubuntu-latest
    needs
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11